server:
  port: 8080
spring:
  application:
    name: mybatis-learning
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_learning?characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    org.apache.ibatis: debug